### ISSUE TITLE
^= unqualified attribute selector

### ISSUE THREAD

**Issue by jonmalave** [zachacole/Simple-Grid#14]
As per CSS Lint `^=` was flagged as an unqualified attribute selector, which indicates a potential performance issue. I'm unfamiliar with this kind of selection `^=`. @zachacole or any other contributor could you explain a bit how this selector works in Simple-Grid, and if this should be of any concern?  

```
.row [class^="col"] {
  float: left;
  margin: 0.5rem 2%;
  min-height: 0.125rem;
}
```

**Comment by zachacole** [comment]
Hi Jon! In CSS, class^="col" targets all the classes whose names begin with col. In the case of Simple Grid, this is going to target all the classes such as .col-1, .col-2, etc...

You can see more about substring matching attributes that were enabled in CSS3 on the w3 spec here: https://www.w3.org/TR/css3-selectors/#attribute-substrings
