### ISSUE TITLE
SASS

### ISSUE THREAD

**Issue by purzlbaum** [zachacole/Simple-Grid#4]
What about a SASS/SCSS version?

**Comment by zachacole** [comment]
Hey @purzlbaum - thanks for the feedback! A number of people have asked about sass as well. I wanted to create a baseline version first that even someone new to CSS could easily use and get started with. I like the idea of expanding to offer a sass version as well - hope to get around to uploading soon. Thanks!

**Comment by zachacole** [comment]
SCSS version is now included in the download package, as well as in the Github repo. Thanks for your patience!
